services:
- type: web
  name: product_management_console
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app